[build]
  base = "/"
  publish = "dist/bestOfReddit/"
  functions = "functions/"

  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate'''
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Access-Control-Allow-Credentials = "true"
    X-Robots-Tag = "all"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin"
    Access-Control-Allow-Origin = "*"
    Clear-Site-Data = "*"
    Accept = "*/*"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=360000"

[[headers]]
  for = "/"
  [headers.values]
    Link = '''
    </*.js.css>; rel=preload; as=script, \
    </styles*.css>; rel=preload; as=style'''
